module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-dim": "#645efb",
        "on-secondary-fixed": "#003a45",
        "tertiary": "#c180ff",
        "secondary-dim": "#40ceed",
        "surface-container-highest": "#202534",
        "secondary-fixed": "#65e1ff",
        "tertiary-fixed-dim": "#c488ff",
        "on-surface": "#e5e7f6",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#1a0099",
        "tertiary-dim": "#9c48ea",
        "on-tertiary-container": "#000000",
        "on-error-container": "#ffb2b9",
        "outline": "#727582",
        "on-tertiary-fixed": "#270048",
        "surface-container-high": "#1a1f2d",
        "outline-variant": "#444854",
        "error": "#ff6e84",
        "background": "#0a0e18",
        "on-tertiary": "#33005b",
        "secondary": "#53ddfc",
        "inverse-on-surface": "#515561",
        "primary": "#a7a5ff",
        "surface-variant": "#202534",
        "secondary-fixed-dim": "#48d4f3",
        "surface": "#0a0e18",
        "tertiary-container": "#af5cfe",
        "inverse-primary": "#4e45e4",
        "on-secondary-container": "#ecfaff",
        "on-primary-container": "#14007e",
        "primary-container": "#9795ff",
        "tertiary-fixed": "#ce9bff",
        "surface-container": "#151926",
        "error-container": "#a70138",
        "surface-container-low": "#0f131e",
        "primary-fixed": "#9795ff",
        "on-secondary": "#004b58",
        "surface-tint": "#a7a5ff",
        "on-surface-variant": "#a7aab9",
        "primary-fixed-dim": "#8885ff",
        "surface-bright": "#262c3c",
        "on-background": "#e5e7f6",
        "surface-container-lowest": "#000000",
        "surface-dim": "#0a0e18",
        "on-secondary-fixed-variant": "#005969",
        "on-error": "#490013",
        "on-primary": "#1c00a0",
        "secondary-container": "#00687a",
        "error-dim": "#d73357",
        "on-tertiary-fixed-variant": "#560094",
        "inverse-surface": "#faf8ff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Space Grotesk"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
